; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using the MEGA Prototyper.
[ MEGAinfo ]
ver                                = 7160617-x86_64 Linux              
[ DataSettings ]
datatype                           = snNucleotide                      
containsCodingNuc                  = False                             
MissingBaseSymbol                  = ?                                 
IdenticalBaseSymbol                = .                                 
GapSymbol                          = -                                 
[ ProcessTypes ]
ppInfer                            = true                              
ppME                               = true                              
[ AnalysisSettings ]
Analysis                           = Phylogeny Reconstruction          
Scope                              = All Selected Taxa                 
Statistical Method                 = Minimum Evolution method          
Phylogeny Test                     = ====================              
Test of Phylogeny                  = None                              
No. of Bootstrap Replications      = Not Applicable                    
Substitution Model                 = ====================              
Substitutions Type                 = Nucleotide                        
Model/Method                       = p-distance                        
Substitutions to Include           = d: Transitions + Transversions    
Rates and Patterns                 = ====================              
Rates among Sites                  = Uniform Rates                     
Gamma Parameter                    = Not Applicable                    
Pattern among Lineages             = Same (Homogeneous)                
Data Subset to Use                 = ====================              
Gaps/Missing Data Treatment        = Partial deletion                  
Site Coverage Cutoff (%)           = 95                                
Tree Inference Options             = ====================              
ME Heuristic Method                = Close-Neighbor-Interchange (CNI)  
Initial Tree for ME                = Obtain initial tree by Neighbor-Joining
ME Search Level                    = 1                                 
Has Time Limit                     = False                             
Maximum Execution Time             = -1                                
